
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class ParserSym {
  /* terminals */
  public static final int ASTERISCO = 4;
  public static final int MENOS = 3;
  public static final int EOF = 0;
  public static final int PARENTESIS_ABRE = 6;
  public static final int MAS = 2;
  public static final int CONSTANTE_ENTERA = 9;
  public static final int error = 1;
  public static final int SHOW = 8;
  public static final int BARRA = 5;
  public static final int PARENTESIS_CIERRA = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAS",
  "MENOS",
  "ASTERISCO",
  "BARRA",
  "PARENTESIS_ABRE",
  "PARENTESIS_CIERRA",
  "SHOW",
  "CONSTANTE_ENTERA"
  };
}

